<a href="https://colab.research.google.com/github/Arif118/Heart-disease-prediction/blob/main/Heart_disease_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [314]:
import pandas as pd

In [315]:
df1 = pd.read_csv('/content/heart.xls')
df2 = pd.read_csv('/content/heart(2).xls')

In [316]:
df1.shape

(1025, 14)

In [317]:
df1.head(4)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0

In [318]:
df2.head(4)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1

In [319]:
df2.shape

(918, 12)

In [320]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [321]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [322]:
df1.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [323]:
df2.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

# Preproccesing Data

In [324]:
df2['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [325]:
df2['cp'] = df2['ChestPainType'].map({
    'ASY': 0,
    'ATA': 1,
    'NAP': 1,
    'TA': 1
})

In [326]:
df2['RestingECG_type'] = df2['RestingECG']

In [327]:
df2['RestingECG'] = df2['RestingECG'].map({
   'Normal': 0,
   'ST': 1,
   'LVH': 1
})

In [328]:
df_extra = [df1['ca'],df1['thal'],df2['ChestPainType'],df2['RestingECG_type']]

In [329]:
df2

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,cp,RestingECG_type
0,40,M,ATA,140,289,0,0,172,N,0.0,Up,0,1,Normal
1,49,F,NAP,160,180,0,0,156,N,1.0,Flat,1,1,Normal
2,37,M,ATA,130,283,0,1,98,N,0.0,Up,0,1,ST
3,48,F,ASY,138,214,0,0,108,Y,1.5,Flat,1,0,Normal
4,54,M,NAP,150,195,0,0,122,N,0.0,Up,0,1,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,0,132,N,1.2,Flat,1,1,Normal
914,68,M,ASY,144,193,1,0,141,N,3.4,Flat,1,0,Normal
915,57,M,ASY,130,131,0,0,115,Y,1.2,Flat,1,0,Normal
916,57,F,ATA,130,236,0,1,174,N,0.0,Flat,1,1,LVH
917,38,M,NAP,138,175,0,0,173,N,0.0,Up,0,1,Normal

In [330]:
df1= df1.drop(['ca','thal'],axis=1)
df2= df2.drop(['ChestPainType','RestingECG_type'],axis=1)

In [331]:
df1.columns = ['Age','Sex','cp','RestingBP','Cholesterol','FastingBS','RestingECG','MaxHR','ExerciseAngina','Oldpeak','ST_Slope','HeartDisease']

# Encoding DF2

In [332]:
from sklearn.preprocessing import LabelEncoder

le= LabelEncoder()
df2['Sex'] = le.fit_transform(df2['Sex'])
df2['ExerciseAngina'] = le.fit_transform(df2['ExerciseAngina'])

In [333]:
df2['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [334]:
df2['ST_Slope'] = df2['ST_Slope'].map({
    'Down': 0,
    'Flat': 0.5,
    'Up': 1
})

In [335]:
df1.head(4)

,Age,Sex,cp,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,52,1,0,125,212,0,1,168,0,1.0,2,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0
3,61,1,0,148,203,0,1,161,0,0.0,2,0

In [336]:
df2.tail(4)

,Age,Sex,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,cp
914,68,1,144,193,1,0,141,0,3.4,0.5,1,0
915,57,1,130,131,0,0,115,1,1.2,0.5,1,0
916,57,0,130,236,0,1,174,0,0.0,0.5,1,1
917,38,1,138,175,0,0,173,0,0.0,1.0,0,1

In [337]:
df = pd.concat([df1,df2])
df

,Age,Sex,cp,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,52,1,0,125,212,0,1,168,0,1.0,2.0,0
1,53,1,0,140,203,1,0,155,1,3.1,0.0,0
2,70,1,0,145,174,0,1,125,1,2.6,0.0,0
3,61,1,0,148,203,0,1,161,0,0.0,2.0,0
4,62,0,0,138,294,1,1,106,0,1.9,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,1,110,264,0,0,132,0,1.2,0.5,1
914,68,1,0,144,193,1,0,141,0,3.4,0.5,1
915,57,1,0,130,131,0,0,115,1,1.2,0.5,1
916,57,0,1,130,236,0,1,174,0,0.0,0.5,1
917,38,1,1,138,175,0,0,173,0,0.0,1.0,0

# Model training

In [338]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier

In [339]:
# Train test split
X = df.drop('HeartDisease', axis=1)
y = df['HeartDisease']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [340]:
model = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    random_state=42
)

In [341]:
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [342]:
#model.predict(X_test)

In [343]:
accuracy = accuracy_score(y_test, model.predict(X_test))
print("Accuracy:", accuracy)

Accuracy: 0.8508997429305912

In [344]:
cross_val_score(model, X_test, y_test, cv=5).mean()

np.float64(0.802131202131202)